services:
  - type: web
    name: website-audit-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        value: YOUR_SUPABASE_URL
      - key: SUPABASE_KEY
        value: YOUR_SUPABASE_ANON_KEY
      - key: GOOGLE_CLIENT_ID
        value: YOUR_GOOGLE_CLIENT_ID
      - key: GOOGLE_CLIENT_SECRET
        value: YOUR_GOOGLE_CLIENT_SECRET
      - key: SECRET_KEY
        value: YOUR_SECRET_KEY_HERE
      - key: FRONTEND_URL
        value: https://your-frontend.render.com