import React from 'react';

const PrivacyPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Privacy Policy</h1>
        
        <div className="bg-white shadow-md rounded-lg p-8">
          <div className="prose prose-blue max-w-none">
            <p className="text-gray-600">
              Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
            
            <h2>Introduction</h2>
            <p>
              Website Tracking Analyzer ("we", "us", or "our") respects your privacy and is committed to protecting your personal data. 
              This privacy policy will inform you about how we look after your personal data when you visit our website and tell you about 
              your privacy rights and how the law protects you.
            </p>
            
            <h2>The Data We Collect</h2>
            <p>
              When you use our Website Tracking Analyzer tool, we process the following data:
            </p>
            <ul>
              <li>The URL you submit for analysis</li>
              <li>Analysis results generated by our tool</li>
              <li>Contact information if you choose to submit it through our contact form</li>
            </ul>
            <p>
              We do not store the analysis results on our servers longer than necessary to provide you with the service.
            </p>
            
            <h2>How We Use Your Data</h2>
            <p>
              We use the data we collect to:
            </p>
            <ul>
              <li>Provide you with our website tracking analysis service</li>
              <li>Respond to your inquiries and contact requests</li>
              <li>Improve our service and user experience</li>
              <li>Ensure the security and proper functioning of our website</li>
            </ul>
            
            <h2>Data Security</h2>
            <p>
              We have implemented appropriate security measures to prevent your personal data from being accidentally lost, 
              used, accessed, altered, or disclosed in an unauthorized way. We limit access to your personal data to those 
              employees, agents, contractors, and other third parties who have a business need to know.
            </p>
            
            <h2>Your Data Protection Rights</h2>
            <p>
              Depending on your location, you may have the following rights:
            </p>
            <ul>
              <li>The right to access your personal data</li>
              <li>The right to rectification of your personal data</li>
              <li>The right to erasure of your personal data</li>
              <li>The right to restrict processing of your personal data</li>
              <li>The right to data portability</li>
              <li>The right to object to processing of your personal data</li>
            </ul>
            
            <h2>Cookies</h2>
            <p>
              Our website uses cookies to distinguish you from other users of our website. This helps us to provide you with 
              a good experience when you browse our website and also allows us to improve our site.
            </p>
            
            <h2>Changes to this Privacy Policy</h2>
            <p>
              We may update our privacy policy from time to time. We will notify you of any changes by posting the new privacy 
              policy on this page and updating the "Last updated" date at the top of this privacy policy.
            </p>
            
            <h2>Contact Us</h2>
            <p>
              If you have any questions about this privacy policy or our privacy practices, please contact us at:
            </p>
            <p>
              Email: privacy@websitetrackinganalyzer.com<br />
              Address: 123 Web Analytics Street, San Francisco, CA 94103
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPage;